<?xml version="1.0"?>
<package format="3">
  <name>ur_sim_bringup</name>
  <version>0.1.0</version>
  <description>World and launch files</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ur_simulation_gz</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
